### ISSUE TITLE
Pluralizing already Plural Names

### ISSUE THREAD

**Issue by rajp33** [molaux/sequelize-graphql-schema-builder#8]
https://github.com/molaux/sequelize-graphql-schema-builder/blob/fda31288474ae5bf01cd936393ca91764448368b/src/lib/nameFormatter.js#L12

Hi,

The sequelize models we are already using, are pluralized to begin with, and when running the schema builder, it is appending an s at the end of each name, so I end up with something like `Accountss`, which isn't ideal. 

Looking through the code, I think this line is the culprit and the condition should be !== instead of ===.

**Comment by molaux** [comment]
Hi,

yes, I consider models names to be singular, and in case pluralize function gives the same name for many, I arbitrary add a `s` to avoid a name conflict.

I think the culprit is `formatManyQueryName` instead, `formatManyModelName` does not seem to be used anymore. But no matter, the cause is the same.

Alternatively, you can implement a different naming strategy by providing your one `nameFormatter` as a `schemaBuilder` option (I realize that it is not documented, [have a look at the code](https://github.com/molaux/sequelize-graphql-schema-builder/blob/master/src/index.js#L77)).
You should have to singularize your model names in `formatModelName`. [The original name formatter factory is exported from the lib so you should just have to tweak it to your needs](https://github.com/molaux/sequelize-graphql-schema-builder/blob/fda31288474ae5bf01cd936393ca91764448368b/src/index.js#L190).

**Comment by rajp33** [comment]
Awesome thank you so much for the clarification!
